#不要修改
Version: 1.0.0

#文字提示
Message_Tip: "§4§l[提示]§e本服无法用铁砧提高拔刀锻造值.请把铁砧放于铁块上,然后对着铁砧shift+右键,即可开启拔刀强化页面"
Message_notSlash: "§4§l[提示]§e你放的这压根不是拔刀"
Message_nothing: "§4§l[提示]§e请把需要强化的拔刀放进去!啥都不放是几个意思?"
Message_NOT_Slash: "§4§l[提示]§e你放的东西连拔刀都不算,脑子秀逗了?"
Message_suc: "§e法克,他居然成功了!"
Message_def: "§4§l[提示]§e失败了!!!嘎哈哈哈,在线玩家获得幸灾乐祸BUFF,防御,移动速度提升!"
Message_def1: "啊哈哈哈恭喜恭喜啊!"
Message_def2: "§e但是你背包里的强化保护符碎裂开,替你保护了拔刀免收损伤"
Message_def3: "§4§l[提示]§e武器...粉碎了!节哀顺变..."
Message_def4: "§e武器强化等级归0"
Message_def5: "§e武器似乎没有受损"
Message_stop: "§4§l[提示]§e材料不足,强化中断"
Message_noVoucher: "§4§l[提示]§e喂,你的强化券跑哪儿去了?"



#此处填写耀魂碎片的id.刀之耀魂用于强化消耗.
SlashId2: 6424



#强化全服公告
#当玩家强化高于某等级的刀，会进行全服强化通报；并且强化失败后全服玩家会自动发出祝福语，全服玩家获得幸灾乐祸buff(增加移速等)
#Broadcast:是否开启全服强化公告,true开启,false关闭
Broadcast: true
#StrengthLimit:强化高于多少等级进行强化公告
StrengthLimit: 11
#FailBuff:是否开启强化失败后在线玩家自动发出祝福语并获得buff的功能？true开启,false关闭。需要Broadcast开启才有效
FailBuff: true



#强化石的ID
id_QHS: 7751

#保护石的ID
id_BHS: 7752

#这里设置强化的成功率,以及相对应的的失败惩罚.
#StrengthLevel表示强化等级.
#chance表示强化等级对应的强化成功率
#punish表示强化失败后掉的等级数.x(小写)表示等级归0,X(大写)表示武器损坏消失
ChanceSetting:
  -
    StrengthLevel: 4
    chance: 100
    punish: 0
    coin: 200
  -
    StrengthLevel: 8
    chance: 80
    punish: 2
    coin: 800
  -
    StrengthLevel: 10
    chance: 50
    punish: 3
    coin: 2000
  -
    StrengthLevel: 15  
    chance: 20
    punish: x
    coin: 5000
  -
    StrengthLevel: max  
    chance: 10
    punish: X
    coin: 10000